export const ERROR_STRING_KEYS = {
  // General
  SOMETHING_WENT_WRONG: 'ERRORS.GENERAL.SOMETHING_WENT_WRONG',
  UNKNOWN_ERROR: 'ERRORS.GENERAL.UNKNOWN_ERROR',
  WRONG_NETWORK: 'ERRORS.GENERAL.WRONG_NETWORK',

  // Delegate
  ADDRESS_IS_OWN_ADDRESS: 'ERRORS.DELEGATE.ADDRESS_IS_OWN_ADDRESS',
  INVALID_ETHEREUM_ADDRESS: 'ERRORS.DELEGATE.INVALID_ETHEREUM_ADDRESS',

  // Stake
  STAKE_MORE_THAN_BALANCE: 'ERRORS.STAKE.STAKE_MORE_THAN_BALANCE',

  // Withdraw
  REQUEST_WITHDRAW_MORE_THAN_BALANCE: 'ERRORS.WITHDRAW.REQUEST_WITHDRAW_MORE_THAN_BALANCE',
  LIQUIDITY_POOL_CURRENT_BLACKOUT_WINDOW: 'ERRORS.WITHDRAW.LIQUIDITY_POOL_CURRENT_BLACKOUT_WINDOW',
};
