export const WARNING_STRING_KEYS = {
  // General
  TRANSFER_LOCK_WARNING: 'WARNINGS.GENERAL.TRANSFER_LOCK_WARNING',

  // Delegation
  TWO_TOKEN_DELEGATION_TRANSACTION: 'WARNINGS.DELEGATION.TWO_TOKEN_DELEGATION_TRANSACTION',
};
